# Generated by Django 4.2.8 on 2023-12-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsvisitor',
            name='visitor_key',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
