# Generated by Django 4.2.8 on 2023-12-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('phone_number', 'phone_number'), ('email', 'email')], default=1, max_length=128),
            preserve_default=False,
        ),
    ]
