# Generated by Django 4.2.8 on 2023-12-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_type',
            field=models.CharField(blank=True, choices=[('phone_number', 'phone_number'), ('email', 'email')], max_length=128, null=True),
        ),
    ]
